[build]
  publish = "."
  command = "" # 无构建命令，留空即可

[[redirects]]
  from = "/api/*"
  to = "https://lu0414jie.free.nf/:splat"
  status = 200
  force = true
  headers = {
    "Access-Control-Allow-Origin" = "*",
    "Access-Control-Allow-Methods" = "GET,POST,OPTIONS",
    "Access-Control-Allow-Headers" = "Content-Type"
  }

[[redirects]]
  from = "/*" # 匹配所有路径，实现单页应用路由兜底
  to = "/index.html"
  status = 200
